### ISSUE TITLE
Worker crashes with "Missing tiktoken_bg.wasm" when using bunx, preventing request logging

### ISSUE THREAD

**Issue by makhweeb** [tombii/better-ccflare#5]
When running `better-ccflare` via `bunx better-ccflare@latest --serve`, the post-processor worker crashes due to a missing `tiktoken_bg.wasm` file. This prevents requests from being saved to the
database, resulting in the `/api/requests` endpoint returning an empty array despite requests being proxied successfully.

## Steps to Reproduce
1. Run the server using `bunx better-ccflare@latest --serve`
2. Send requests through the proxy (e.g., `POST /v1/messages`)
3. Check `/api/requests?limit=200`
4. Observe that the endpoint returns `[]` (empty array)
5. Check logs and see the worker error

## Expected Behavior
- Requests should be saved to the database after processing
- `/api/requests` endpoint should return a list of proxied requests with usage statistics
- No WASM-related errors in logs

## Actual Behavior
- Worker crashes with error: `Missing tiktoken_bg.wasm`
- Requests are NOT saved to the database
- `/api/requests` endpoint returns empty array
- Console logs show the request is processed but database save fails

## Error Logs
[2025-10-23T07:57:55.452Z] ERROR: [Proxy] Worker error occurred in usage tracking system
...
error: Missing tiktoken_bg.wasm
      at blob:1c42973a-41fc-4a24-86a9-e6546fe385f6:317:9448
      at loadAndEvaluateModule (1:11)
      at moduleEvaluation (1:11)
      at loadAndEvaluateModule (2:1)

## Console Logs Show Proxying Works
[2025-10-23T07:58:33.513Z] INFO: [Proxy] Selected 1 accounts: 200_1
[2025-10-23T07:58:33.513Z] INFO: [Proxy] Request: POST /v1/messages
[2025-10-23T07:58:33.514Z] INFO: [ProxyOperations] Attempting request with account: 200_1

## Environment
- Runtime: Bun
- Installation method: `bunx better-ccflare@latest --serve`
- OS: Linux (production server with supervisord)
- Version: 1.2.31

## Root Cause
The `@dqbd/tiktoken` package requires `tiktoken_bg.wasm` to be accessible at runtime. When using `bunx`, the package is cached in a temporary location and the WASM file path resolution fails,
causing the worker to crash before `dbOps.saveRequest()` can execute.

**Comment by tombii** [comment]
## ✅ Fixed in v1.2.33

This issue has been resolved by embedding the tiktoken WASM file directly into the compiled binary.

### What was changed:
- The tiktoken lite WASM file (1.1MB) is now embedded as base64 during the build process
- The post-processor worker loads the WASM from the embedded data at runtime
- This applies to all build methods: npm packages, GitHub releases, and Docker images

### How to get the fix:

**Option 1: npm/bunx (available now)**
```bash
npx better-ccflare@latest --serve
# or
bunx better-ccflare@latest --serve
```

**Option 2: GitHub releases (building now)**
The multi-arch binaries are being built by GitHub Actions. They will be available at:
https://github.com/tombii/better-ccflare/releases/tag/v1.2.33

**Option 3: Docker (will be available after release completes)**
```bash
docker pull ghcr.io/tombii/better-ccflare:1.2.33
```

### Testing:
Please verify that the fix works for you by testing with `bunx better-ccflare@latest --serve`. The worker should initialize successfully and requests should be logged to the database.

You can verify by:
1. Running the proxy
2. Making some requests through it
3. Checking `/api/requests?limit=10` - you should see your requests listed

Let me know if you still encounter any issues!

---
Commit: 7db7ee1

**Comment by bitcoin4cashqc** [comment]
Nah not fixed for me for sure : 

```
line@lineccflare:~/better-ccflare$ bun run build
$ bun run build:dashboard && bun run build:tui
$ bun run --cwd packages/dashboard-web build
$ bun run build.ts

🚀 Building dashboard...

🗑️ Cleaning previous build at /home/line/better-ccflare/packages/dashboard-web/dist
📄 Building dashboard from src/index.html

✅ Dashboard build completed in 1930.88ms

📦 Output files:
   - dist/chunk-tcpvm8ak.js
   - dist/index.html
   - dist/chunk-da502fym.js
   - dist/chunk-3eqyx416.js
   - dist/chunk-rycabrsv.css
   - dist/chunk-tcpvm8ak.js.map
   - dist/chunk-da502fym.js.map
   - dist/chunk-3eqyx416.js.map
   - dist/favicon-7fef0tsq.svg

📦 Generating embedded assets...
✅ Embedded assets generated at dist/embedded.ts
$ bun run --cwd apps/tui build
$ mkdir -p dist && BETTER_CCFLARE_VERSION=$(node -p "require('./package.json').version") bun build ../../packages/proxy/src/post-processor.worker.ts --outfile dist/post-processor.worker.js --target=bun --minify && bun -e "const fs=require('fs'); const code=fs.readFileSync('dist/post-processor.worker.js','utf8'); const encoded=Buffer.from(code).toString('base64'); fs.writeFileSync('../../packages/proxy/src/inline-worker.ts', 'export const EMBEDDED_WORKER_CODE = \"' + encoded + '\";'); const wasm=fs.readFileSync('../../node_modules/@dqbd/tiktoken/lite/tiktoken_bg.wasm'); const wasmEncoded=wasm.toString('base64'); fs.writeFileSync('../../packages/proxy/src/embedded-tiktoken-wasm.ts', 'export const EMBEDDED_TIKTOKEN_WASM = \"' + wasmEncoded + '\";');" && bun build src/main.ts --compile --outfile dist/better-ccflare --target=bun --minify --define process.env.BETTER_CCFLARE_VERSION='"'$BETTER_CCFLARE_VERSION'"' && rm -f dist/post-processor.worker.js
18 | import { EMBEDDED_TIKTOKEN_WASM } from "./embedded-tiktoken-wasm";
                                            ^
error: Could not resolve: "./embedded-tiktoken-wasm"
    at /home/line/better-ccflare/packages/proxy/src/post-processor.worker.ts:18:40
error: script "build" exited with code 1
error: script "build:tui" exited with code 1
error: script "build" exited with code 1
```

Im able to build the dashboard and the server but not tui and analytics doesnt work in the frontend

**Comment by tombii** [comment]
@bitcoin4cashqc I can't reproduce it. Just remove the whole directory and start from git clone again.
Your settings are on the home folder so they should be saved anyway.

**Comment by tombii** [comment]
> Which settings are in home?
> 
> Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
> […](#)

The DB with all the settings
